# тестовая последовательность для сервера
date  
host_name  
pwd  
list  
mul 12.5 1.8  
sum 2.7 8.4  
solve 0 12 36  
solve 1 12 36  
solve 2 12 6  
rename file1.ext file2.ext  
rename index.html file1.ext  
list  
rename file1.ext index.html  
list  
delete file1.ext  
delete index.html  
list
date
shutdown
